apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sv9eqaxr2-go 
  janus-idp.io/tekton: sv9eqaxr2-go
  backstage.io/kubernetes-id: sv9eqaxr2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sv9eqaxr2-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml