apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sv9eqaxr2-go-gitops
  description: This is GitOps manifest for sv9eqaxr2-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=sv9eqaxr2-go
    backstage.io/kubernetes-id: sv9eqaxr2-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sv9eqaxr2-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sv9eqaxr2-go
