apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sv9eqaxr2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sv9eqaxr2-go 
  name: sv9eqaxr2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sv9eqaxr2-go 
